service: serverless-http-endpoints

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-express

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: handler.handler  #assuming your handler file is handler.js
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'